name: Simple Matrix and Cache Demo

on:
  push:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ v1, v2, v3 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ðŸ‘‡ CACHE SECTION INGA THAAN
    - name: Cache folder
      uses: actions/cache@v4
      with:
        path: cache-folder
        key: ${{ runner.os }}-${{ matrix.version }}-${{ hashFiles('message.txt') }}

    - name: Create folder & file
      run: |
        mkdir -p cache-folder
        echo "Hello ${{ matrix.version }}" > cache-folder/info.txt

    - name: Show file
      run: cat cache-folder/info.txt

